### ISSUE TITLE
Советы по оформлению кода

### ISSUE THREAD

**Issue by Vlad-Bondar** [VladislavLiudchyk/LoseIt#1]
# Советы по оформлению кода

##### 1.1.1 Структура классов
- поле date следует объявить локально (DailyDiet.java)
- поле dbService следует объявить локально (EditMealActivity.java)
##### 1.1.2 Актуальность кода (Использование устаревшего API)
- метод getColor() (SearchNutrientsActivity.java; строка 134)
- методы getYear(), getMonth(), getDate() (MainActivity.java, строка 164)
##### 1.1.3 Вопросы, связанные с проблемами кода
- ненужный символ ";" (AppData.java; строка 14)
- ненужный символ ";" (MainActivity.java; строка 317)
##### 1.1.4 Проблемы, связанные с JavaDoc
- описание тега пропущено (ListItemAdapter.java; строка 28)
- описание тега пропущено (MainActivity.java; строка 209)
##### 1.1.5 Вероятные ошибки
- неиспользуемое присваивание (ListItemAdapter.java; строка 24)
- конструкция "if" с пустым телом (ListItemAdapter.java; строка 55)

##### 1.2.1 Доступность
- отсутствует атрибут "contentDescription" для изображения (activity_launch_app.xml)
##### 1.2.2 Дизайн и интернационализация
- Жестко привязанный к программе текст (activity_main.xml)
- Симметричность отступов (при задании paddingLeft следует задавать paddingRight для симметрии)
##### 1.2.3 Производительность
- Слишком длинный путь вектора изображения (871 символ).
- Отрисовка областей более одного раза в файлах разметки (использование androidBackground и @app/Theme с таким же androidBackground)
- неиспользуемые элементы в файлах русурсов

##### 1.2.4 Юзабилити
- В файлах разметки используется атрибут "showAsActions=always". Предпочтительнее испоьзовать "showAsActions=ifRoom"
- В некоторых файлах разметки пропущен атрибут "inputType"

### 2. Правильность написания 
- некорректные названия элементов

**Comment by lyudchik** [comment]
Замечания учтены, были внесены изменения
